name: Build Debian Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Cross-compile Go for Raspberry Pi
        run: |
          GOOS=linux GOARCH=arm GOARM=7 go build -o myprogram-bin

      - name: Create Debian Package Structure
        run: |
          # Create the folder structure
          mkdir -p myprogram-deb/DEBIAN
          echo "Package: myprogram" >> myprogram-deb/DEBIAN/control
          echo "Version: 1.0.0" >> myprogram-deb/DEBIAN/control
          echo "Architecture: armhf" >> myprogram-deb/DEBIAN/control
          echo "Maintainer: Your Name <youremail@example.com>" >> myprogram-deb/DEBIAN/control
          echo "Description: My Go program for Raspberry Pi" >> myprogram-deb/DEBIAN/control
          
          # Move the compiled binary to the correct folder in the package
          mkdir -p myprogram-deb/usr/local/bin
          mv myprogram-bin myprogram-deb/usr/local/bin/myprogram

      - name: Build the .deb package
        run: |
          dpkg-deb --build myprogram-deb

      - name: Upload the .deb package as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: myprogram.deb
          path: ./myprogram-deb.deb
